/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ga.tc.authentication.ui;

import com.ga.tc.authentication.bao.UserBao;
import com.ga.tc.authentication.bao.UserBaoImpl;
import com.ga.tc.authentication.dto.UserInfoDto;
import com.ga.tc.authentication.ui.tables.models.UserTableCellEditor;
import com.ga.tc.authentication.ui.tables.models.UserTableCellRenderer;
import com.ga.tc.authentication.ui.tables.models.UsersTableModel;
import com.ga.tc.common.ConnectionFactory;
import com.ga.tc.common.Constants;
import com.ga.tc.reports.ReportsUtil;
import com.ga.tc.security.dao.SecurityDao;
import com.ga.tc.security.dao.SecurityDaoImpl;
import com.ga.tc.security.dto.RoleInfoDto;
import java.sql.Connection;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author pc
 */
public class AllUsers extends javax.swing.JPanel {

    private UserBao business = new UserBaoImpl();
    private SecurityDao secBusiness = new SecurityDaoImpl();
    /**
     * Creates new form AllUsers
     */
    public AllUsers() {
        initComponents();
        usersTable.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("All Users List"));

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        fillInUsersTable();
        jScrollPane1.setViewportView(usersTable);

        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String reportPath = "D:\\2- Current Work\\Online Training\\Java track\\5. JSE Wordkshop\\Netbeans_Project\\TC_APP\\src\\com\\ga\\tc\\reports\\tc_users.jrxml";
            Map<String,Object> params = null;
            if(ReportsUtil.exportReport(reportPath, params));
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error While Exporting the Report:\n"+ e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

    private void fillInUsersTable() {
        try{
            List<UserInfoDto> users = business.listAll(Constants.STATUS_LIST_ALL);
            /**
             * Custom Table Model
             */
            List<RoleInfoDto> allRoles =secBusiness.listAll(Constants.STATUS_LIST_ALL);
            for(int index = 0; index<users.size() ; index++){
                for(RoleInfoDto role:allRoles){
                    if(users.get(index).getRole().getId().equals(role.getId()))
                        users.get(index).setRole(role);
                }
            }
            usersTable.setModel(new UsersTableModel(users));
            usersTable.setDefaultRenderer(RoleInfoDto.class, new UserTableCellRenderer());
            usersTable.setDefaultEditor(RoleInfoDto.class ,new UserTableCellEditor(null, allRoles));
            /**
             * End of Custom table model
             */
                    
//            Object [][] usersModel = new Object[users.size()][7];
//            if(users != null && !users.isEmpty()){
//                for(int row =0; row<users.size();row++){
//                    usersModel[row][0] = users.get(row).getId();
//                    usersModel[row][1] = users.get(row).getFullName();
//                    usersModel[row][2] = users.get(row).getEmail();
//                    usersModel[row][3] = users.get(row).getPassword();
//                    usersModel[row][4] = users.get(row).getPhone();
//                    usersModel[row][5] = users.get(row).getAddress();
//                    usersModel[row][6] = users.get(row).getRoleId();
//                }
//            }
//            String [] headers = new String [] {"User Id", "User Name","Email", "Password", "Phone", "Address", "Role"};
//            usersTable.setModel(new javax.swing.table.DefaultTableModel(usersModel, headers));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error Ocuured :"+
                    e.getMessage(), "Error" ,JOptionPane.ERROR_MESSAGE);
        }
    }
}
