/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ga.tc.authentication.ui;

import com.ga.tc.authentication.bao.UserBao;
import com.ga.tc.authentication.bao.UserBaoImpl;
import com.ga.tc.authentication.dto.UserInfoDto;
import com.ga.tc.common.LAF;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class ManageMyProfile extends javax.swing.JPanel {
    private UserBao business = new UserBaoImpl();
    private Vector<LAF> lafComboModel = new Vector<>();
    /**
     * Creates new form ManageMyProfile
     */
    public ManageMyProfile() {
        initComponents();
    }
    private UserInfoDto userInfo;
    public ManageMyProfile(UserInfoDto userInfo) {
        initComponents();
        
        this.userInfo = userInfo;
        /**
         * Instantiate the components from the userInfo bean
         */
        fullnameTxt.setText(userInfo.getFullName());
        emailTxt.setText(userInfo.getEmail());
        phoneTxt.setText(userInfo.getPhone());
        addressTxt.setText(userInfo.getAddress());
        /** 
         * Search 4 the selected index
         */
        int index = -1;
        for(LAF l: lafComboModel){
            if(userInfo.getLaf().equals(l.getClassName())){
                lafsCombo.setSelectedItem(l);
                break;
            }
        }       
                   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lafsCombo = new javax.swing.JComboBox<>();
        fullnameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        msglbl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Edit my Profile"));

        jLabel1.setText("Full Name:");

        jLabel2.setText("Address:");

        phoneLbl.setText("Phone:");

        jLabel4.setText("Email:");

        jLabel5.setText("Theme");

        lafsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fillInLAFs();

        jButton1.setText("Update My Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        msglbl.setForeground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(phoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fullnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lafsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(fullnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(jLabel2)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lafsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(msglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            boolean hasError = false, useDefaultPassword = false;
            StringBuffer sb = new StringBuffer("");
            if("".equals(fullnameTxt.getText().trim())){
                hasError = true;
                sb.append("- Full name is required.");
            }
            if("".equals(emailTxt.getText().trim())){
                hasError = true;
                sb.append("- Email is required.");
            }
//            if(((LAF)lafsCombo.getSelectedItem()).getClass() == null){
            if(lafsCombo.getSelectedIndex() == 0){
                hasError = true;  
                sb.append("- LAF is required.");
            }
            
            if(hasError){
                msglbl.setVisible(true);
                msglbl.setText(sb.toString());
            }else{
                msglbl.setVisible(false);
                UserInfoDto user  = new UserInfoDto();
                //fill-in the user information from the UI
                user.setFullName(fullnameTxt.getText().trim());
                user.setEmail(emailTxt.getText().trim());
                user.setPhone(phoneTxt.getText().trim());
                user.setAddress(addressTxt.getText().trim());
                LAF selected = (LAF)lafsCombo.getModel().getSelectedItem();
                user.setLaf(selected.getClassName());
                user.setId(userInfo.getId());
                
                if(business.updateUserProfile(user)){
                    JOptionPane.showMessageDialog(this, "User profile is saved sucessfully" ,"Success", JOptionPane.INFORMATION_MESSAGE);
                }else
                    JOptionPane.showMessageDialog(this, "User profile is NOT saved sucessfully" ,"Error", JOptionPane.ERROR_MESSAGE);
            }
    
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, "Error :"+e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fullnameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> lafsCombo;
    private javax.swing.JLabel msglbl;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    // End of variables declaration//GEN-END:variables

    
    private void fillInLAFs() {
        //INITIATE LAF COMBO.
        lafComboModel.addElement(new LAF("-- Select --",null));
        lafComboModel.addElement(new LAF("Aero","com.jtattoo.plaf.aero.AeroLookAndFeel"));
        lafComboModel.addElement(new LAF("Aluminium","com.jtattoo.plaf.aluminium.AluminiumLookAndFeel"));
        lafComboModel.addElement(new LAF("Bernstein","com.jtattoo.plaf.bernstein.BernsteinLookAndFeel"));
        lafComboModel.addElement(new LAF("HI FI","com.jtattoo.plaf.hifi.HiFiLookAndFeel"));
        lafComboModel.addElement(new LAF("Luna", "com.jtattoo.plaf.luna.LunaLookAndFeel"));
        lafComboModel.addElement(new LAF("McWin","com.jtattoo.plaf.mcwin.McWinLookAndFeel"));
        lafComboModel.addElement(new LAF("Mint","com.jtattoo.plaf.mint.MintLookAndFeel"));
        lafComboModel.addElement(new LAF("Noire","com.jtattoo.plaf.noire.NoireLookAndFeel"));
        lafComboModel.addElement(new LAF("SmarT","com.jtattoo.plaf.smart.SmartLookAndFeel"));
        lafComboModel.addElement(new LAF("Texture","com.jtattoo.plaf.texture.TextureLookAndFeel"));
        lafComboModel.addElement(new LAF("Acry","com.jtattoo.plaf.acryl.AcrylLookAndFeel"));
        lafComboModel.addElement(new LAF("Aluminium","com.jtattoo.plaf.aluminium.AluminiumLookAndFeel"));
        lafComboModel.addElement(new LAF("Texture","com.jtattoo.plaf.texture.TextureLookAndFeel"));
        lafsCombo = new JComboBox(lafComboModel);
    }
}
