/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ga.tc.authentication.ui;

import com.ga.tc.authentication.dto.UserInfoDto;
import com.ga.tc.common.Constants;
import com.ga.tc.security.bao.SecurityBao;
import com.ga.tc.security.bao.SecurityBaoImpl;
import com.ga.tc.security.dto.ScreenDto;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class ScreenManager extends javax.swing.JPanel {
    private SecurityBao business =  new SecurityBaoImpl();
    /**
     * Creates new form ScreenManager
     */
    public ScreenManager() {
        initComponents();
    }
    private UserInfoDto userInfo;
    public ScreenManager(UserInfoDto userInfo) {
        this();
        this.userInfo = userInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameArTxt = new javax.swing.JTextField();
        nameEnTxt = new javax.swing.JTextField();
        activeChk = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        codeCombo = new javax.swing.JComboBox<>();
        errorLbl = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        screensTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Screen Manager"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New Screen"));

        jLabel1.setText("Arabic Name");

        jLabel2.setText("Unique Code");

        jLabel3.setText("English Name");

        jLabel4.setText("Active?");

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/ga/tc/common/lang"); // NOI18N
        jButton1.setText(bundle.getString("security.screens.save_btn")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        codeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fillInScreenCodesCombo();

        errorLbl.setForeground(new java.awt.Color(255, 0, 51));

        deleteBtn.setText(bundle.getString("security.screens.delete_btn")); // NOI18N
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jButton3.setText(bundle.getString("security.screens.rest_btn")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nameArTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameEnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activeChk)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(codeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameEnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(activeChk))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(nameArTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(codeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addComponent(errorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(deleteBtn)))
                .addGap(40, 40, 40))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("All Screens"));

        screensTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        initializeScreensTable();
        screensTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                screensTableMouseReleased(evt);
            }
        });
        screensTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                screensTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(screensTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        try{
            //validation
            StringBuffer sb = new StringBuffer("");
            if(nameArTxt.getText().trim().equals(""))
                sb.append("- Arabic name is MUST.");
            if(nameEnTxt.getText().trim().equals("")){
                sb.append("- English name is MUST.");
            }
            if(!sb.toString().equals("")){
                errorLbl.setText(sb.toString());
                errorLbl.setVisible(true);
            }else{
                //call business to save
                errorLbl.setVisible(false);
                ScreenDto screen = null;
                screen = (selectedScreenId == -1)? 
                        new ScreenDto(codeCombo.getSelectedItem().toString(),nameArTxt.getText().trim(), nameEnTxt.getText().trim(), true)
                      : new ScreenDto(selectedScreenId, codeCombo.getSelectedItem().toString(),nameArTxt.getText().trim(), nameEnTxt.getText().trim(), true);
                if(business.save(screen)>0){
                    JOptionPane.showMessageDialog(this, "Screen have been added successfully :)");
                    //add newley inserted row to the screens table
                    if(selectedScreenId == -1){
                        DefaultTableModel model =  (DefaultTableModel)screensTable.getModel();
                        model.addRow(new Object[]{"", nameArTxt.getText(), nameEnTxt.getText(), codeCombo.getSelectedItem(), activeChk.isSelected()});
                        nameArTxt.setText("");
                        nameEnTxt.setText("");
                    }else{
                        DefaultTableModel model =  (DefaultTableModel)screensTable.getModel();
                        model.setValueAt(nameArTxt.getText(), screensTable.getSelectedRow(), 1);
                        model.setValueAt(nameEnTxt.getText(), screensTable.getSelectedRow(), 2);
                        model.setValueAt(codeCombo.getSelectedItem(), screensTable.getSelectedRow(), 3);
                        model.setValueAt(activeChk.isSelected(), screensTable.getSelectedRow(), 4);
                        screensTable.setModel(model);
                        selectedScreenId= -1;
                        nameArTxt.setText("");
                        nameEnTxt.setText("");
                    
                    }
                        
                }else
                    JOptionPane.showMessageDialog(this, "Something went wrong :( try agina later");
            }
                
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error:\n"+e.getMessage());
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed
    private Integer selectedScreenId= -1;
    private String [] headers = new String [] {
                    "#", "إسم عربي", "English Name", "Code", "Active"};   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            selectedScreenId= -1;
            //rest the new form
            nameArTxt .setText("");
            nameEnTxt .setText("");
            activeChk.setSelected(false);
            
            
            //refresh the table
            screensTable.setModel(new DefaultTableModel(null, headers));
            List<ScreenDto> screens = business.listAllScreens(Constants.STATUS_LIST_ALL);
            for(ScreenDto s:screens){
                ((DefaultTableModel)screensTable.getModel()).addRow(new Object[]{s.getId(), s.getNameAr(), s.getNameEn(), s.getCode(), s.isActive()});
            }
            /////////////////////////
            updateMode = false;
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error:\n"+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    private boolean updateMode = false;
    private void screensTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_screensTableMouseReleased
        updateScreenFormFromTable();
    }//GEN-LAST:event_screensTableMouseReleased

    private void screensTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_screensTableKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 38 || evt.getKeyCode() == 40)
            updateScreenFormFromTable();
    }//GEN-LAST:event_screensTableKeyReleased

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you wanna delete this screen?");
        if(answer == 0){
            if(screensTable.getSelectedRow() != -1){
                String code = (String)((DefaultTableModel)screensTable.getModel())
                        .getValueAt(screensTable.getSelectedRow(), 3);
                if(business.deleteScr(code)){
                    DefaultTableModel model =  (DefaultTableModel)screensTable.getModel();
                    model.removeRow(screensTable.getSelectedRow());
                    screensTable.setModel(model);
                    nameArTxt.setText("");
                    nameEnTxt.setText("");
                    JOptionPane.showMessageDialog(this, "Screen deleted successfuly :)");
                    selectedScreenId= -1;
                }else
                    JOptionPane.showMessageDialog(this, "Something went wrong please try again :(");
            }else{
                JOptionPane.showMessageDialog(this, "Please Select  Screen first!!");
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activeChk;
    private javax.swing.JComboBox<String> codeCombo;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameArTxt;
    private javax.swing.JTextField nameEnTxt;
    private javax.swing.JTable screensTable;
    // End of variables declaration//GEN-END:variables

    private void fillInScreenCodesCombo() {
        codeCombo = new JComboBox<>(com.ga.tc.common.Constants.SCREENS_CODES);
    }

    private void initializeScreensTable() {
        try{
            List<ScreenDto> screens = business.listAllScreens(Constants.STATUS_LIST_ALL);
            Object [][] data = new Object[screens.size()][5];
            for(int i=0;i<screens.size();i++){
                data[i][0] = screens.get(i).getId();
                data[i][1] = screens.get(i).getNameAr();
                data[i][2] = screens.get(i).getNameEn();
                data[i][3] = screens.get(i).getCode();
                data[i][4] = screens.get(i).isActive();
            }
            
             
        
            DefaultTableModel model = new DefaultTableModel(data, headers);
            screensTable = new JTable(model){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
                
                @Override
                public Class<?> getColumnClass(int column) {
                    switch(column){
                       case 0:
                           return Integer.class;
                       case 1:
                           return String.class;
                       case 2:
                           return String.class;
                       case 3:
                           return String.class;
                       case 4:
                           return Boolean.class;
                       default:
                           return Integer.class;
                   }   
                }
                
            };
               
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void updateScreenFormFromTable() {
        // TODO add your handling code here:
        try{
            int index = screensTable.getSelectedRow();
            selectedScreenId = Integer.parseInt(screensTable.getValueAt(index, 0).toString());
            nameArTxt.setText(screensTable.getValueAt(index, 1).toString());
            nameEnTxt.setText(screensTable.getValueAt(index, 2).toString());
            codeCombo.setSelectedItem(screensTable.getValueAt(index, 3).toString());
            activeChk.setSelected((Boolean)screensTable.getValueAt(index, 4));
            updateMode = true;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please Press Refresh First !!!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error:\n"+e.getMessage());
        }
    }
}
